name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      # Install dependencies using Makefile
      - name: Install dependencies
        run: make install
        working-directory: VitalTrackServer

      # Set environment variables (requires GitHub Secrets)
      - name: Set environment variables
        env:
          MONGO_API_KEY: ${{ secrets.MONGO_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FINED_TUNED_MODEL: ${{ secrets.FINED_TUNED_MODEL }}
          OPENAI_SYSTEM_MESSAGE: ${{ secrets.OPENAI_SYSTEM_MESSAGE }}
        run: make set-env
        working-directory: VitalTrackServer

      # Lint Python code using Makefile
      - name: Lint Python code
        run: make lint
        working-directory: VitalTrackServer

      # Run Python unit tests using Makefile
      - name: Run Python tests
        run: make test
        working-directory: VitalTrackServer
