name: React Native Frontend

on:
  push:
    branches: [ "MaryJabro" ]
  pull_request:
    branches: [ "MaryJabro" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Node.js for the React Native environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    # Install dependencies 
    - name: Install dependencies
      working-directory: VitalTrackApp  
      run: |
        npm install

    # Run ESLint in the correct directory
    - name: Lint with ESLint
      working-directory: VitalTrackApp  
      run: |
        npm run lint

    # Run Jest 
    - name: Test with Jest
      working-directory: VitalTrackApp  
      run: |
        npm run test

    #  Build the project
    - name: Build the project
      working-directory: VitalTrackApp  
      run: |
        npm run build
