name: React Native Frontend CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 17 for Android
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Install Android SDK Command-line Tools
      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
          mkdir -p $HOME/Android/cmdline-tools
          unzip commandlinetools-linux-8092744_latest.zip -d $HOME/Android/cmdline-tools
          export ANDROID_HOME=$HOME/Android
          export PATH=$ANDROID_HOME/cmdline-tools/cmdline-tools/bin:$PATH
          sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Set up Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Run Gradle tasks
      - name: Run Gradle Build
        working-directory: VitalTrackApp
        run: gradle build
